### PR TITLE
Fix typo in argsObserver variable name

### LINKED ISSUE #66: New error throw during testing in v10.2.1 due to typo with `argsObserver`
I believe this change caused an issue because `argsObserver` is a typo and should be `argObserver`:
https://github.com/wc-toolkit/storybook-helpers/commit/3345f754c2fe54515f646a0cdf55a1c3d9afde4b

I am seeing this error when running tests:
```
ReferenceError: argsObserver is not defined
 ❯ ../../node_modules/@wc-toolkit/storybook-helpers/dist/index.js:730:29
```

### PR DESCRIPTION
**Pull request by stefanonepanedap**
Should fix https://github.com/wc-toolkit/storybook-helpers/issues/66

### CODE REVIEW

**Review by break-stuff — APPROVED** [review]

File: src/html-templates.ts [hunk 1]
```diff
@@ -352,7 +352,7 @@ function syncControls(component: Component) {
   setTimeout(() => {
     const selectedComponent = document.querySelector(component.tagName!);
     if (selectedComponent && argsObserver) {
```
Comment (regexpert) [inline src/html-templates.ts]: please update the name of `argsObserver` here, because there is only `argObserver` in this module

**Review by regexpert — CHANGES_REQUESTED** [review]

**Review by regexpert — APPROVED** [review]

File: src/html-templates.ts (hunk 1 above)
Comment (break-stuff) [reply src/html-templates.ts]: I think it was correct. It's observing multiple args.

Comment (regexpert) [reply src/html-templates.ts]: but `argsObserver` is not defined anywhere, so this code looks dead in this case
or do you mean that need to update name of `argObserver` variable everywhere?

Comment (break-stuff) [reply src/html-templates.ts]: Ah, you are correct. Thanks!

**Review by break-stuff — APPROVED** [review]

**Comment by rubencarvalho** [comment]
Is it possible this PR was missing a changeset? I ran into the same issue and was wondering if a release is coming soon 😄
